

services:
  mysqldb:
    image: mysql:8
    container_name: hotel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: hoteldb
    ports:
      - "3310:3306"
    volumes:
      - hotel_mysql_data:/var/lib/mysql
    networks:
      - hotel-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pdocker"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: hotel-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/hoteldb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: docker
    ports:
      - "2080:2080"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - hotel-net
    restart: on-failure

  frontend:
    image: priyankasml/hotel-frontend:latest
    container_name: hotel-frontend
    ports:
      - "3005:80"
    depends_on:
      - backend
    networks:
      - hotel-net
    restart: on-failure

volumes:
  hotel_mysql_data:

networks:
  hotel-net:
